name: Drupal CI - Code Standards Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpcs:
    name: Drupal Coding Standards Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer, phpcs

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Register Drupal coding standard
        run: |
          ./vendor/bin/phpcs --config-set installed_paths ./vendor/drupal/coder/coder_sniffer
          ./vendor/bin/phpcs -i  # Debug check: shows Drupal & DrupalPractice now installed

      - name: Run PHPCS on custom modules
        run: ./vendor/bin/phpcs --standard=Drupal web/modules/custom
