name: Drupal CI - Code Standards Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpcs:
    name: Drupal Coding Standards Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPCS with manually defined standard path
        run: |
          ./vendor/bin/phpcs \
            --standard=./vendor/drupal/coder/coder_sniffer/Drupal \
            web/modules/custom
